apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: react-app
        image: <baibhav225/react-native-app>:<16>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-react-app
  ports:
    - port: 80
      targetPort: 80
