apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: react-app
        image: baibhav225/react-native-app:${BUILD_NUMBER}
        ports:
        - containerPort: 19000
        - containerPort: 19001
        - containerPort: 19002
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-react-app
  ports:
    - name: expo
      port: 19000
      targetPort: 19000
    - name: metro
      port: 19001
      targetPort: 19001
    - name: devtools
      port: 19002
      targetPort: 19002
